import os

FILE_PATH = r"c:\Users\imano\OneDrive\Escritorio\proyectos\painpoint_scraper\frontend\src\app\(app)\dashboard\page.tsx"

with open(FILE_PATH, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    '"Todas"': '"All"',
    'selectedNiche === "Todas"': 'selectedNiche === "All"',
    '# Reporte de Oportunidades Generadas por IA': '# AI Generated Opportunities Report',
    'Metodología de Venture Research (NicheHunter)': 'Venture Research Methodology (NicheHunter)',
    'Analizamos **${selectedOpportunities.length} clústeres** de dolor en el mercado y descartamos **${discardedOpportunities.length}** por falta de evidencia o monetización.': 'We analyzed **${selectedOpportunities.length}** pain clusters in the market and discarded **${discardedOpportunities.length}** due to lack of evidence or monetization.',
    'Las ideas sobrevivientes se clasifican en **Tiers (A, B, C)** ponderando Potencial Financiero y Confianza Estadística.': 'Surviving ideas are classified into **Tiers (A, B, C)** weighting Financial Potential and Statistical Confidence.',
    'Resumen Ejecutivo': 'Executive Summary',
    '👑 Tier A: Oportunidades Doradas (Alto Potencial + Alta Evidencia)': '👑 Tier A: Golden Opportunities (High Potential + High Evidence)',
    'Confianza: ${opp.confidence_score || \'N/A\'}% | Detectado en': 'Confidence: ${opp.confidence_score || \'N/A\'}% | Detected in',
    'hilos.': 'threads.',
    '🚀 Tier B: Hipótesis Prometedoras (Alto Potencial + Evidencia Limitada)': '🚀 Tier B: Promising Hypotheses (High Potential + Limited Evidence)',
    'Confianza: ${opp.confidence_score || \'N/A\'}%)': 'Confidence: ${opp.confidence_score || \'N/A\'}%)',
    'Análisis Detallado': 'Detailed Analysis',
    'Dolor detectado': 'Pain detected',
    'Evidencia': 'Evidence',
    'posts independientes': 'independent posts',
    'upvotes combinados': 'combined upvotes',
    'comentarios': 'comments',
    'Clientes': 'Customers',
    'Competidores': 'Competitors',
    'Diferenciación': 'Differentiation',
    'Riesgo': 'Risk',
    'Potencial Financiero': 'Financial Potential',
    'Fórmula: Base 4.0 + Viralidad': 'Formula: Base 4.0 + Virality',
    'Frecuencia': 'Frequency',
    'Penalizaciones': 'Penalties',
    'Confianza de Datos': 'Data Confidence',
    'Basado en volumen y recurrencia histórica': 'Based on volume and historical recurrence',
    'Veredicto': 'Verdict',
    'Oportunidad válida': 'Valid opportunity',
    'Tipo de Problema': 'Problem Type',
    'Dolor Agudo': 'Acute Pain',
    'Riesgos de Fracaso (Inversor Escéptico)': 'Failure Risks (Skeptic Investor)',
    'Tendencias': 'Trends',
    'Fuentes de Reddit': 'Reddit Sources',
    'Oportunidades Descartadas (Filtro de Ruido)': 'Discarded Opportunities (Noise Filter)',
    'Las siguientes ideas fueron analizadas pero descartadas por la IA para proteger la viabilidad del negocio o por su bajo score potencial.': 'The following ideas were analyzed but discarded by the AI to protect business viability or due to their low potential score.',
    'Bajo potencial / Ruido': 'Low potential / Noise',
    '¿Qué nicho deseas infiltrar hoy?': 'Which niche do you want to infiltrate today?',
    'Ej: Startups, Freelance, Inmobiliarias...': 'Ex: Startups, Freelance, Real Estate...',
    'Procesando...': 'Processing...',
    'Extraer': 'Extract',
    'Conectando al servidor de IA...': 'Connecting to AI server...',
    'Error Crítico en el Pipeline': 'Critical Pipeline Error',
    'Fallo desconocido.': 'Unknown failure.',
    'Cerrar y Volver': 'Close and Return',
    'Terreno Seco': 'Dry Ground',
    'No encontramos suficientes quejas (solo': 'Not enough complaints found (only',
    'posts analizados para el nicho': 'analyzed posts for niche',
    'Saber que un nicho no tiene demanda validada te acaba de ahorrar semanas de trabajo. Explora otro nicho. No se ha cobrado ninguna moneda.': 'Knowing a niche has no validated demand just saved you weeks of work. Explore another niche. No coins were charged.',
    'Explorar nuevo nicho': 'Explore new niche',
    'Terreno Explorador': 'Explorer Terrain',
    'Resultados preliminares para:': 'Preliminary results for:',
    'Calidad Estimada': 'Estimated Quality',
    '>ALTA<': '>HIGH<',
    'Posts Relevantes': 'Relevant Posts',
    'Quejas Detectadas': 'Complaints Detected',
    'Costo del análisis profundo:': 'Deep analysis cost:',
    '1 Moneda': '1 Coin',
    'Cancelar': 'Cancel',
    'Analizando...': 'Analyzing...',
    'Analizar en Profundidad': 'Analyze in Depth',
    'No tienes suficientes monedas.': 'You do not have enough coins.',
    'Análisis Terminado: 0 Oportunidades': 'Analysis Finished: 0 Opportunities',
    'A pesar de encontrar quejas, la IA VC Escéptica determinó que ninguna tiene el potencial financiero o modelo de negocio viable para justificar una startup (Score bajo).': 'Despite finding complaints, the Skeptic VC AI determined none have the financial potential or viable business model to justify a startup (Low Score).',
    'Se te ha reembolsado 1 moneda automáticamente.': '1 coin has been automatically refunded to you.',
    'Oportunidades Guardadas': 'Saved Opportunities',
    'Válidas': 'Valid',
    'Descartadas': 'Discarded',
    'Exportar a Markdown': 'Export to Markdown',
    'Filtro de Calidad Activado': 'Quality Filter Activated',
    'Se analizaron oportunidades, pero todas fueron descartadas por tener un Score de Potencial demasiado bajo (≤ 4.5). Hemos evitado mostrarte falsos positivos.': 'Opportunities were analyzed, but all were discarded for having a Potential Score too low (≤ 4.5). We prevented showing you false positives.',
    '(Exporta a Markdown para ver la lista de ideas descartadas)': '(Export to Markdown to see the list of discarded ideas)',
    '¿Seguro que quieres borrar esta oportunidad?': 'Are you sure you want to delete this opportunity?',
    'Eliminar oportunidad': 'Delete opportunity',
    'Tier A (Dorada)': 'Tier A (Golden)',
    'Tier B (Prometedora)': 'Tier B (Promising)',
    'Tier C (Nicho)': 'Tier C (Niche)',
    'Confianza:': 'Confidence:',
    'Riesgo:': 'Risk:',
    'Validación': 'Validation',
    'Público Objetivo (Quién paga)': 'Target Audience (Who pays)',
    'No definido': 'Not defined',
    'Dificultad Técnica': 'Technical Difficulty',
    'Media': 'Medium',
    'Pagos (WTP)': 'Payments (WTP)',
    'Alta': 'High',
    'Baja': 'Low',
    'El Problema': 'The Problem',
    'Por qué esta idea podría fracasar (Análisis Crítico)': 'Why this idea could fail (Critical Analysis)',
    'No provisto': 'Not provided',
    'Análisis de Mercado': 'Market Analysis',
    'Competencia': 'Competition',
    'Modelo de Monetización': 'Monetization Model',
    'Nichos Emergentes': 'Emerging Niches',
    'El Toque de Oro (Fuentes Originales)': 'The Golden Touch (Original Sources)',
    'Eliminar': 'Delete',
    'Cerrar': 'Close'
}

for es, en in replacements.items():
    content = content.replace(es, en)

with open(FILE_PATH, "w", encoding="utf-8") as f:
    f.write(content)

print("Translation completed successfully.")
