"""Agregada columna url a raw_posts

Revision ID: 07eb6ebf6c8a
Revises: 9128424b77d0
Create Date: 2026-04-24 14:57:36.030570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07eb6ebf6c8a'
down_revision: Union[str, Sequence[str], None] = '9128424b77d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
