"""make opportunity agnostic

Revision ID: 3365b341da4a
Revises: 73d79ffde81f
Create Date: 2026-06-19 14:42:56.310018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3365b341da4a'
down_revision: Union[str, Sequence[str], None] = '73d79ffde81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('source_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('opportunities', 'reddit_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('reddit_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('opportunities', 'source_links')
    # ### end Alembic commands ###
