"""Add tier and confidence

Revision ID: 472805b59bc1
Revises: 4d826cb33acf
Create Date: 2026-06-04 13:40:58.722879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472805b59bc1'
down_revision: Union[str, Sequence[str], None] = '4d826cb33acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('confidence_score', sa.Integer(), nullable=True))
    op.add_column('opportunities', sa.Column('tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'tier')
    op.drop_column('opportunities', 'confidence_score')
    # ### end Alembic commands ###
