"""Add skeptic investor fields

Revision ID: 4d826cb33acf
Revises: 8698bb9032bb
Create Date: 2026-06-04 12:33:49.740121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d826cb33acf'
down_revision: Union[str, Sequence[str], None] = '8698bb9032bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('problem_type', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('failure_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pain_point_clusters', sa.Column('cluster_cohesion', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pain_point_clusters', 'cluster_cohesion')
    op.drop_column('opportunities', 'failure_risks')
    op.drop_column('opportunities', 'problem_type')
    # ### end Alembic commands ###
