"""Add ValidationReport

Revision ID: 5c6ccb24ccb9
Revises: 9f59d28a1812
Create Date: 2026-06-25 13:19:19.333466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6ccb24ccb9'
down_revision: Union[str, Sequence[str], None] = '9f59d28a1812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('clerk_org_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], unique=True)
    op.drop_constraint(op.f('pain_point_clusters_scan_job_id_fkey'), 'pain_point_clusters', type_='foreignkey')
    op.create_foreign_key(None, 'pain_point_clusters', 'scan_jobs', ['scan_job_id'], ['id'], ondelete='CASCADE')
    op.add_column('scan_jobs', sa.Column('target_industry', sa.String(), nullable=True))
    op.add_column('scan_jobs', sa.Column('business_process', sa.String(), nullable=True))
    op.drop_column('validation_reports', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_reports', sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('scan_jobs', 'business_process')
    op.drop_column('scan_jobs', 'target_industry')
    op.drop_constraint(None, 'pain_point_clusters', type_='foreignkey')
    op.create_foreign_key(op.f('pain_point_clusters_scan_job_id_fkey'), 'pain_point_clusters', 'scan_jobs', ['scan_job_id'], ['id'])
    op.drop_index(op.f('ix_organizations_clerk_org_id'), table_name='organizations')
    op.drop_column('organizations', 'clerk_org_id')
    # ### end Alembic commands ###
