"""Add user_id to ScanJob

Revision ID: 6595ec2d3c44
Revises: 86dd63c5dba1
Create Date: 2026-05-27 12:23:09.585772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6595ec2d3c44'
down_revision: Union[str, Sequence[str], None] = '86dd63c5dba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'scan_jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_jobs', type_='foreignkey')
    op.drop_column('scan_jobs', 'user_id')
    # ### end Alembic commands ###
