"""make rawpost agnostic

Revision ID: 73d79ffde81f
Revises: 9b062cb48be4
Create Date: 2026-06-19 14:41:26.714341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d79ffde81f'
down_revision: Union[str, Sequence[str], None] = '9b062cb48be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_posts', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('raw_posts', sa.Column('source_platform', sa.String(), nullable=True))
    op.add_column('raw_posts', sa.Column('source_community', sa.String(), nullable=True))
    op.add_column('raw_posts', sa.Column('engagement_score', sa.Integer(), nullable=True))
    op.add_column('raw_posts', sa.Column('reply_count', sa.Integer(), nullable=True))
    op.add_column('raw_posts', sa.Column('source_created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_raw_posts_reddit_id'), table_name='raw_posts')
    op.create_index(op.f('ix_raw_posts_source_id'), 'raw_posts', ['source_id'], unique=True)
    op.drop_column('raw_posts', 'num_comments')
    op.drop_column('raw_posts', 'reddit_created_at')
    op.drop_column('raw_posts', 'score')
    op.drop_column('raw_posts', 'reddit_id')
    op.drop_column('raw_posts', 'subreddit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_posts', sa.Column('subreddit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_posts', sa.Column('reddit_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_posts', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('raw_posts', sa.Column('reddit_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('raw_posts', sa.Column('num_comments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_raw_posts_source_id'), table_name='raw_posts')
    op.create_index(op.f('ix_raw_posts_reddit_id'), 'raw_posts', ['reddit_id'], unique=True)
    op.drop_column('raw_posts', 'source_created_at')
    op.drop_column('raw_posts', 'reply_count')
    op.drop_column('raw_posts', 'engagement_score')
    op.drop_column('raw_posts', 'source_community')
    op.drop_column('raw_posts', 'source_platform')
    op.drop_column('raw_posts', 'source_id')
    # ### end Alembic commands ###
