"""add market size to validation reports

Revision ID: 7f9490d2aa40
Revises: 5c6ccb24ccb9
Create Date: 2026-06-25 15:00:15.768067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9490d2aa40'
down_revision: Union[str, Sequence[str], None] = '5c6ccb24ccb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_reports', sa.Column('market_size_tam', sa.String(), nullable=True))
    op.add_column('validation_reports', sa.Column('market_growth_cagr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_reports', 'market_growth_cagr')
    op.drop_column('validation_reports', 'market_size_tam')
    # ### end Alembic commands ###
