"""premium_report_fields

Revision ID: 8698bb9032bb
Revises: e4548de4b21c
Create Date: 2026-05-30 18:58:30.688821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8698bb9032bb'
down_revision: Union[str, Sequence[str], None] = 'e4548de4b21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('total_comments', sa.Integer(), nullable=True))
    op.add_column('opportunities', sa.Column('target_audience', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('differentiation', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('mvp', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('risk', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('verdict', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'verdict')
    op.drop_column('opportunities', 'risk')
    op.drop_column('opportunities', 'mvp')
    op.drop_column('opportunities', 'differentiation')
    op.drop_column('opportunities', 'target_audience')
    op.drop_column('opportunities', 'total_comments')
    # ### end Alembic commands ###
