"""Agregada columna url a raw_posts

Revision ID: 9128424b77d0
Revises: 59937155235b
Create Date: 2026-04-24 14:52:37.936525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9128424b77d0'
down_revision: Union[str, Sequence[str], None] = '59937155235b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_posts', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_posts', 'url')
    # ### end Alembic commands ###
