"""Add phase and coins to ScanJob, credits to User

Revision ID: 9b062cb48be4
Revises: 472805b59bc1
Create Date: 2026-06-07 14:49:02.386704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b062cb48be4'
down_revision: Union[str, Sequence[str], None] = '472805b59bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('phase', sa.String(), nullable=True))
    op.add_column('scan_jobs', sa.Column('cost_coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('credits_remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits_remaining')
    op.drop_column('scan_jobs', 'cost_coins')
    op.drop_column('scan_jobs', 'phase')
    # ### end Alembic commands ###
