"""Add validation reports and remove gamification

Revision ID: 9f59d28a1812
Revises: 3365b341da4a
Create Date: 2026-06-25 13:11:06.329969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f59d28a1812'
down_revision: Union[str, Sequence[str], None] = '3365b341da4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('report_title', sa.String(), nullable=True),
    sa.Column('friction_summary', sa.Text(), nullable=True),
    sa.Column('cost_of_inaction', sa.Text(), nullable=True),
    sa.Column('audience_profile', sa.String(), nullable=True),
    sa.Column('existing_alternatives', sa.Text(), nullable=True),
    sa.Column('competitor_gaps', sa.Text(), nullable=True),
    sa.Column('trend_velocity', sa.String(), nullable=True),
    sa.Column('risk_profile', sa.Text(), nullable=True),
    sa.Column('willingness_to_pay', sa.String(), nullable=True),
    sa.Column('validation_verdict', sa.String(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('total_upvotes', sa.Integer(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=True),
    sa.Column('source_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['pain_point_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('saved_opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_opportunities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('saved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('saved_opportunities_opportunity_id_fkey')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('saved_opportunities_org_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_opportunities_pkey'))
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cluster_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('problem_statement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_solutions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monetization_ideas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('competitive_landscape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('opportunity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('strategies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('post_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('urgency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('willingness_to_pay', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('temporal_trends', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emerging_niches', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_upvotes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_audience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('differentiation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mvp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verdict', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('problem_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('failure_risks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['pain_point_clusters.id'], name=op.f('opportunities_cluster_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunities_pkey'))
    )
    op.drop_table('validation_reports')
    # ### end Alembic commands ###
