"""Add credibility fields

Revision ID: a57dd5af1d5d
Revises: 7f9490d2aa40
Create Date: 2026-07-01 12:18:37.658629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a57dd5af1d5d'
down_revision: Union[str, Sequence[str], None] = '7f9490d2aa40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('competitors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('validation_reports', sa.Column('tam_cagr_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_reports', 'tam_cagr_sources')
    op.drop_column('scan_jobs', 'competitors')
    # ### end Alembic commands ###
