"""Add evidence and strategy fields

Revision ID: be6edd13d2d5
Revises: a57dd5af1d5d
Create Date: 2026-07-01 15:04:19.501152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be6edd13d2d5'
down_revision: Union[str, Sequence[str], None] = 'a57dd5af1d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_reports', sa.Column('top_pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validation_reports', sa.Column('representative_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validation_reports', sa.Column('demand_score', sa.Float(), nullable=True))
    op.add_column('validation_reports', sa.Column('pain_severity_score', sa.Float(), nullable=True))
    op.add_column('validation_reports', sa.Column('competition_score', sa.Float(), nullable=True))
    op.add_column('validation_reports', sa.Column('overall_confidence_score', sa.Float(), nullable=True))
    op.add_column('validation_reports', sa.Column('opportunity_score', sa.Float(), nullable=True))
    op.add_column('validation_reports', sa.Column('strategic_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validation_reports', sa.Column('opportunity_why', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validation_reports', sa.Column('recommended_positioning', sa.Text(), nullable=True))
    op.add_column('validation_reports', sa.Column('mvp_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_reports', 'mvp_features')
    op.drop_column('validation_reports', 'recommended_positioning')
    op.drop_column('validation_reports', 'opportunity_why')
    op.drop_column('validation_reports', 'strategic_recommendations')
    op.drop_column('validation_reports', 'opportunity_score')
    op.drop_column('validation_reports', 'overall_confidence_score')
    op.drop_column('validation_reports', 'competition_score')
    op.drop_column('validation_reports', 'pain_severity_score')
    op.drop_column('validation_reports', 'demand_score')
    op.drop_column('validation_reports', 'representative_quotes')
    op.drop_column('validation_reports', 'top_pain_points')
    # ### end Alembic commands ###
