"""add_daas_metrics

Revision ID: c369e720bbb2
Revises: 6595ec2d3c44
Create Date: 2026-05-29 13:48:53.971290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c369e720bbb2'
down_revision: Union[str, Sequence[str], None] = '6595ec2d3c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('post_count', sa.Integer(), nullable=True))
    op.add_column('opportunities', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('urgency', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('willingness_to_pay', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('temporal_trends', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('emerging_niches', sa.String(), nullable=True))
    op.add_column('opportunities', sa.Column('reddit_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'reddit_links')
    op.drop_column('opportunities', 'emerging_niches')
    op.drop_column('opportunities', 'temporal_trends')
    op.drop_column('opportunities', 'willingness_to_pay')
    op.drop_column('opportunities', 'urgency')
    op.drop_column('opportunities', 'sentiment')
    op.drop_column('opportunities', 'post_count')
    # ### end Alembic commands ###
