"""add_total_upvotes

Revision ID: e4548de4b21c
Revises: c369e720bbb2
Create Date: 2026-05-29 15:54:15.915753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4548de4b21c'
down_revision: Union[str, Sequence[str], None] = 'c369e720bbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('total_upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'total_upvotes')
    # ### end Alembic commands ###
